/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ParentRouteImport } from './routes/parent'
import { Route as OperatorRouteImport } from './routes/operator'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ParentReportsRouteImport } from './routes/parent/reports'
import { Route as ParentProgressRouteImport } from './routes/parent/progress'
import { Route as ParentNotificationsRouteImport } from './routes/parent/notifications'
import { Route as ParentFeesRouteImport } from './routes/parent/fees'
import { Route as ParentExamsRouteImport } from './routes/parent/exams'
import { Route as ParentDashboardRouteImport } from './routes/parent/dashboard'
import { Route as ParentAttendanceRouteImport } from './routes/parent/attendance'
import { Route as OperatorDashboardRouteImport } from './routes/operator/dashboard'
import { Route as AdminVerificationRouteImport } from './routes/admin/verification'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminPtmRouteImport } from './routes/admin/ptm'
import { Route as AdminPerformanceRouteImport } from './routes/admin/performance'
import { Route as AdminFeesRouteImport } from './routes/admin/fees'
import { Route as AdminExamsRouteImport } from './routes/admin/exams'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminAuditTrailRouteImport } from './routes/admin/audit-trail'
import { Route as AdminAttendanceRouteImport } from './routes/admin/attendance'
import { Route as AdminApprovalsRouteImport } from './routes/admin/approvals'
import { Route as AdminActivitiesRouteImport } from './routes/admin/activities'
import { Route as OperatorSubmissionsIndexRouteImport } from './routes/operator/submissions/index'
import { Route as OperatorMarksIndexRouteImport } from './routes/operator/marks/index'
import { Route as OperatorFeesIndexRouteImport } from './routes/operator/fees/index'
import { Route as OperatorFeedbackIndexRouteImport } from './routes/operator/feedback/index'
import { Route as OperatorExamsIndexRouteImport } from './routes/operator/exams/index'
import { Route as OperatorBulkIndexRouteImport } from './routes/operator/bulk/index'
import { Route as OperatorAttendanceIndexRouteImport } from './routes/operator/attendance/index'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminTeachersIndexRouteImport } from './routes/admin/teachers/index'
import { Route as AdminStudentsIndexRouteImport } from './routes/admin/students/index'
import { Route as AdminClassesIndexRouteImport } from './routes/admin/classes/index'
import { Route as AdminAdmissionsIndexRouteImport } from './routes/admin/admissions/index'
import { Route as AdminTeachersNewRouteImport } from './routes/admin/teachers/new'
import { Route as AdminStudentsNewRouteImport } from './routes/admin/students/new'
import { Route as AdminStudentsStudentIdIndexRouteImport } from './routes/admin/students/$studentId/index'
import { Route as AdminTeachersTeacherIdEditRouteImport } from './routes/admin/teachers/$teacherId/edit'
import { Route as AdminStudentsStudentIdEditRouteImport } from './routes/admin/students/$studentId/edit'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentRoute = ParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorRoute = OperatorRouteImport.update({
  id: '/operator',
  path: '/operator',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentReportsRoute = ParentReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ParentRoute,
} as any)
const ParentProgressRoute = ParentProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => ParentRoute,
} as any)
const ParentNotificationsRoute = ParentNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => ParentRoute,
} as any)
const ParentFeesRoute = ParentFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => ParentRoute,
} as any)
const ParentExamsRoute = ParentExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => ParentRoute,
} as any)
const ParentDashboardRoute = ParentDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ParentRoute,
} as any)
const ParentAttendanceRoute = ParentAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => ParentRoute,
} as any)
const OperatorDashboardRoute = OperatorDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => OperatorRoute,
} as any)
const AdminVerificationRoute = AdminVerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPtmRoute = AdminPtmRouteImport.update({
  id: '/ptm',
  path: '/ptm',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPerformanceRoute = AdminPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeesRoute = AdminFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExamsRoute = AdminExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditTrailRoute = AdminAuditTrailRouteImport.update({
  id: '/audit-trail',
  path: '/audit-trail',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAttendanceRoute = AdminAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApprovalsRoute = AdminApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivitiesRoute = AdminActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => AdminRoute,
} as any)
const OperatorSubmissionsIndexRoute =
  OperatorSubmissionsIndexRouteImport.update({
    id: '/submissions/',
    path: '/submissions/',
    getParentRoute: () => OperatorRoute,
  } as any)
const OperatorMarksIndexRoute = OperatorMarksIndexRouteImport.update({
  id: '/marks/',
  path: '/marks/',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorFeesIndexRoute = OperatorFeesIndexRouteImport.update({
  id: '/fees/',
  path: '/fees/',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorFeedbackIndexRoute = OperatorFeedbackIndexRouteImport.update({
  id: '/feedback/',
  path: '/feedback/',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorExamsIndexRoute = OperatorExamsIndexRouteImport.update({
  id: '/exams/',
  path: '/exams/',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorBulkIndexRoute = OperatorBulkIndexRouteImport.update({
  id: '/bulk/',
  path: '/bulk/',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorAttendanceIndexRoute = OperatorAttendanceIndexRouteImport.update({
  id: '/attendance/',
  path: '/attendance/',
  getParentRoute: () => OperatorRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeachersIndexRoute = AdminTeachersIndexRouteImport.update({
  id: '/teachers/',
  path: '/teachers/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsIndexRoute = AdminStudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClassesIndexRoute = AdminClassesIndexRouteImport.update({
  id: '/classes/',
  path: '/classes/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdmissionsIndexRoute = AdminAdmissionsIndexRouteImport.update({
  id: '/admissions/',
  path: '/admissions/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeachersNewRoute = AdminTeachersNewRouteImport.update({
  id: '/teachers/new',
  path: '/teachers/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsNewRoute = AdminStudentsNewRouteImport.update({
  id: '/students/new',
  path: '/students/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsStudentIdIndexRoute =
  AdminStudentsStudentIdIndexRouteImport.update({
    id: '/students/$studentId/',
    path: '/students/$studentId/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminTeachersTeacherIdEditRoute =
  AdminTeachersTeacherIdEditRouteImport.update({
    id: '/teachers/$teacherId/edit',
    path: '/teachers/$teacherId/edit',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminStudentsStudentIdEditRoute =
  AdminStudentsStudentIdEditRouteImport.update({
    id: '/students/$studentId/edit',
    path: '/students/$studentId/edit',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/operator': typeof OperatorRouteWithChildren
  '/parent': typeof ParentRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/admin/activities': typeof AdminActivitiesRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/audit-trail': typeof AdminAuditTrailRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/exams': typeof AdminExamsRoute
  '/admin/fees': typeof AdminFeesRoute
  '/admin/performance': typeof AdminPerformanceRoute
  '/admin/ptm': typeof AdminPtmRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/operator/dashboard': typeof OperatorDashboardRoute
  '/parent/attendance': typeof ParentAttendanceRoute
  '/parent/dashboard': typeof ParentDashboardRoute
  '/parent/exams': typeof ParentExamsRoute
  '/parent/fees': typeof ParentFeesRoute
  '/parent/notifications': typeof ParentNotificationsRoute
  '/parent/progress': typeof ParentProgressRoute
  '/parent/reports': typeof ParentReportsRoute
  '/admin/students/new': typeof AdminStudentsNewRoute
  '/admin/teachers/new': typeof AdminTeachersNewRoute
  '/admin/admissions/': typeof AdminAdmissionsIndexRoute
  '/admin/classes/': typeof AdminClassesIndexRoute
  '/admin/students/': typeof AdminStudentsIndexRoute
  '/admin/teachers/': typeof AdminTeachersIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/operator/attendance/': typeof OperatorAttendanceIndexRoute
  '/operator/bulk/': typeof OperatorBulkIndexRoute
  '/operator/exams/': typeof OperatorExamsIndexRoute
  '/operator/feedback/': typeof OperatorFeedbackIndexRoute
  '/operator/fees/': typeof OperatorFeesIndexRoute
  '/operator/marks/': typeof OperatorMarksIndexRoute
  '/operator/submissions/': typeof OperatorSubmissionsIndexRoute
  '/admin/students/$studentId/edit': typeof AdminStudentsStudentIdEditRoute
  '/admin/teachers/$teacherId/edit': typeof AdminTeachersTeacherIdEditRoute
  '/admin/students/$studentId/': typeof AdminStudentsStudentIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/operator': typeof OperatorRouteWithChildren
  '/parent': typeof ParentRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/admin/activities': typeof AdminActivitiesRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/audit-trail': typeof AdminAuditTrailRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/exams': typeof AdminExamsRoute
  '/admin/fees': typeof AdminFeesRoute
  '/admin/performance': typeof AdminPerformanceRoute
  '/admin/ptm': typeof AdminPtmRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/operator/dashboard': typeof OperatorDashboardRoute
  '/parent/attendance': typeof ParentAttendanceRoute
  '/parent/dashboard': typeof ParentDashboardRoute
  '/parent/exams': typeof ParentExamsRoute
  '/parent/fees': typeof ParentFeesRoute
  '/parent/notifications': typeof ParentNotificationsRoute
  '/parent/progress': typeof ParentProgressRoute
  '/parent/reports': typeof ParentReportsRoute
  '/admin/students/new': typeof AdminStudentsNewRoute
  '/admin/teachers/new': typeof AdminTeachersNewRoute
  '/admin/admissions': typeof AdminAdmissionsIndexRoute
  '/admin/classes': typeof AdminClassesIndexRoute
  '/admin/students': typeof AdminStudentsIndexRoute
  '/admin/teachers': typeof AdminTeachersIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/operator/attendance': typeof OperatorAttendanceIndexRoute
  '/operator/bulk': typeof OperatorBulkIndexRoute
  '/operator/exams': typeof OperatorExamsIndexRoute
  '/operator/feedback': typeof OperatorFeedbackIndexRoute
  '/operator/fees': typeof OperatorFeesIndexRoute
  '/operator/marks': typeof OperatorMarksIndexRoute
  '/operator/submissions': typeof OperatorSubmissionsIndexRoute
  '/admin/students/$studentId/edit': typeof AdminStudentsStudentIdEditRoute
  '/admin/teachers/$teacherId/edit': typeof AdminTeachersTeacherIdEditRoute
  '/admin/students/$studentId': typeof AdminStudentsStudentIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/operator': typeof OperatorRouteWithChildren
  '/parent': typeof ParentRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/admin/activities': typeof AdminActivitiesRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/audit-trail': typeof AdminAuditTrailRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/exams': typeof AdminExamsRoute
  '/admin/fees': typeof AdminFeesRoute
  '/admin/performance': typeof AdminPerformanceRoute
  '/admin/ptm': typeof AdminPtmRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/operator/dashboard': typeof OperatorDashboardRoute
  '/parent/attendance': typeof ParentAttendanceRoute
  '/parent/dashboard': typeof ParentDashboardRoute
  '/parent/exams': typeof ParentExamsRoute
  '/parent/fees': typeof ParentFeesRoute
  '/parent/notifications': typeof ParentNotificationsRoute
  '/parent/progress': typeof ParentProgressRoute
  '/parent/reports': typeof ParentReportsRoute
  '/admin/students/new': typeof AdminStudentsNewRoute
  '/admin/teachers/new': typeof AdminTeachersNewRoute
  '/admin/admissions/': typeof AdminAdmissionsIndexRoute
  '/admin/classes/': typeof AdminClassesIndexRoute
  '/admin/students/': typeof AdminStudentsIndexRoute
  '/admin/teachers/': typeof AdminTeachersIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/operator/attendance/': typeof OperatorAttendanceIndexRoute
  '/operator/bulk/': typeof OperatorBulkIndexRoute
  '/operator/exams/': typeof OperatorExamsIndexRoute
  '/operator/feedback/': typeof OperatorFeedbackIndexRoute
  '/operator/fees/': typeof OperatorFeesIndexRoute
  '/operator/marks/': typeof OperatorMarksIndexRoute
  '/operator/submissions/': typeof OperatorSubmissionsIndexRoute
  '/admin/students/$studentId/edit': typeof AdminStudentsStudentIdEditRoute
  '/admin/teachers/$teacherId/edit': typeof AdminTeachersTeacherIdEditRoute
  '/admin/students/$studentId/': typeof AdminStudentsStudentIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/operator'
    | '/parent'
    | '/reset-password'
    | '/admin/activities'
    | '/admin/approvals'
    | '/admin/attendance'
    | '/admin/audit-trail'
    | '/admin/dashboard'
    | '/admin/exams'
    | '/admin/fees'
    | '/admin/performance'
    | '/admin/ptm'
    | '/admin/settings'
    | '/admin/verification'
    | '/operator/dashboard'
    | '/parent/attendance'
    | '/parent/dashboard'
    | '/parent/exams'
    | '/parent/fees'
    | '/parent/notifications'
    | '/parent/progress'
    | '/parent/reports'
    | '/admin/students/new'
    | '/admin/teachers/new'
    | '/admin/admissions/'
    | '/admin/classes/'
    | '/admin/students/'
    | '/admin/teachers/'
    | '/admin/users/'
    | '/operator/attendance/'
    | '/operator/bulk/'
    | '/operator/exams/'
    | '/operator/feedback/'
    | '/operator/fees/'
    | '/operator/marks/'
    | '/operator/submissions/'
    | '/admin/students/$studentId/edit'
    | '/admin/teachers/$teacherId/edit'
    | '/admin/students/$studentId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/operator'
    | '/parent'
    | '/reset-password'
    | '/admin/activities'
    | '/admin/approvals'
    | '/admin/attendance'
    | '/admin/audit-trail'
    | '/admin/dashboard'
    | '/admin/exams'
    | '/admin/fees'
    | '/admin/performance'
    | '/admin/ptm'
    | '/admin/settings'
    | '/admin/verification'
    | '/operator/dashboard'
    | '/parent/attendance'
    | '/parent/dashboard'
    | '/parent/exams'
    | '/parent/fees'
    | '/parent/notifications'
    | '/parent/progress'
    | '/parent/reports'
    | '/admin/students/new'
    | '/admin/teachers/new'
    | '/admin/admissions'
    | '/admin/classes'
    | '/admin/students'
    | '/admin/teachers'
    | '/admin/users'
    | '/operator/attendance'
    | '/operator/bulk'
    | '/operator/exams'
    | '/operator/feedback'
    | '/operator/fees'
    | '/operator/marks'
    | '/operator/submissions'
    | '/admin/students/$studentId/edit'
    | '/admin/teachers/$teacherId/edit'
    | '/admin/students/$studentId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/operator'
    | '/parent'
    | '/reset-password'
    | '/admin/activities'
    | '/admin/approvals'
    | '/admin/attendance'
    | '/admin/audit-trail'
    | '/admin/dashboard'
    | '/admin/exams'
    | '/admin/fees'
    | '/admin/performance'
    | '/admin/ptm'
    | '/admin/settings'
    | '/admin/verification'
    | '/operator/dashboard'
    | '/parent/attendance'
    | '/parent/dashboard'
    | '/parent/exams'
    | '/parent/fees'
    | '/parent/notifications'
    | '/parent/progress'
    | '/parent/reports'
    | '/admin/students/new'
    | '/admin/teachers/new'
    | '/admin/admissions/'
    | '/admin/classes/'
    | '/admin/students/'
    | '/admin/teachers/'
    | '/admin/users/'
    | '/operator/attendance/'
    | '/operator/bulk/'
    | '/operator/exams/'
    | '/operator/feedback/'
    | '/operator/fees/'
    | '/operator/marks/'
    | '/operator/submissions/'
    | '/admin/students/$studentId/edit'
    | '/admin/teachers/$teacherId/edit'
    | '/admin/students/$studentId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OperatorRoute: typeof OperatorRouteWithChildren
  ParentRoute: typeof ParentRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent': {
      id: '/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof ParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator': {
      id: '/operator'
      path: '/operator'
      fullPath: '/operator'
      preLoaderRoute: typeof OperatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent/reports': {
      id: '/parent/reports'
      path: '/reports'
      fullPath: '/parent/reports'
      preLoaderRoute: typeof ParentReportsRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/progress': {
      id: '/parent/progress'
      path: '/progress'
      fullPath: '/parent/progress'
      preLoaderRoute: typeof ParentProgressRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/notifications': {
      id: '/parent/notifications'
      path: '/notifications'
      fullPath: '/parent/notifications'
      preLoaderRoute: typeof ParentNotificationsRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/fees': {
      id: '/parent/fees'
      path: '/fees'
      fullPath: '/parent/fees'
      preLoaderRoute: typeof ParentFeesRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/exams': {
      id: '/parent/exams'
      path: '/exams'
      fullPath: '/parent/exams'
      preLoaderRoute: typeof ParentExamsRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/dashboard': {
      id: '/parent/dashboard'
      path: '/dashboard'
      fullPath: '/parent/dashboard'
      preLoaderRoute: typeof ParentDashboardRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/attendance': {
      id: '/parent/attendance'
      path: '/attendance'
      fullPath: '/parent/attendance'
      preLoaderRoute: typeof ParentAttendanceRouteImport
      parentRoute: typeof ParentRoute
    }
    '/operator/dashboard': {
      id: '/operator/dashboard'
      path: '/dashboard'
      fullPath: '/operator/dashboard'
      preLoaderRoute: typeof OperatorDashboardRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/admin/verification': {
      id: '/admin/verification'
      path: '/verification'
      fullPath: '/admin/verification'
      preLoaderRoute: typeof AdminVerificationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ptm': {
      id: '/admin/ptm'
      path: '/ptm'
      fullPath: '/admin/ptm'
      preLoaderRoute: typeof AdminPtmRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/performance': {
      id: '/admin/performance'
      path: '/performance'
      fullPath: '/admin/performance'
      preLoaderRoute: typeof AdminPerformanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fees': {
      id: '/admin/fees'
      path: '/fees'
      fullPath: '/admin/fees'
      preLoaderRoute: typeof AdminFeesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/exams': {
      id: '/admin/exams'
      path: '/exams'
      fullPath: '/admin/exams'
      preLoaderRoute: typeof AdminExamsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit-trail': {
      id: '/admin/audit-trail'
      path: '/audit-trail'
      fullPath: '/admin/audit-trail'
      preLoaderRoute: typeof AdminAuditTrailRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/attendance': {
      id: '/admin/attendance'
      path: '/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AdminAttendanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/approvals': {
      id: '/admin/approvals'
      path: '/approvals'
      fullPath: '/admin/approvals'
      preLoaderRoute: typeof AdminApprovalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/activities': {
      id: '/admin/activities'
      path: '/activities'
      fullPath: '/admin/activities'
      preLoaderRoute: typeof AdminActivitiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/operator/submissions/': {
      id: '/operator/submissions/'
      path: '/submissions'
      fullPath: '/operator/submissions/'
      preLoaderRoute: typeof OperatorSubmissionsIndexRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/operator/marks/': {
      id: '/operator/marks/'
      path: '/marks'
      fullPath: '/operator/marks/'
      preLoaderRoute: typeof OperatorMarksIndexRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/operator/fees/': {
      id: '/operator/fees/'
      path: '/fees'
      fullPath: '/operator/fees/'
      preLoaderRoute: typeof OperatorFeesIndexRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/operator/feedback/': {
      id: '/operator/feedback/'
      path: '/feedback'
      fullPath: '/operator/feedback/'
      preLoaderRoute: typeof OperatorFeedbackIndexRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/operator/exams/': {
      id: '/operator/exams/'
      path: '/exams'
      fullPath: '/operator/exams/'
      preLoaderRoute: typeof OperatorExamsIndexRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/operator/bulk/': {
      id: '/operator/bulk/'
      path: '/bulk'
      fullPath: '/operator/bulk/'
      preLoaderRoute: typeof OperatorBulkIndexRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/operator/attendance/': {
      id: '/operator/attendance/'
      path: '/attendance'
      fullPath: '/operator/attendance/'
      preLoaderRoute: typeof OperatorAttendanceIndexRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/teachers/': {
      id: '/admin/teachers/'
      path: '/teachers'
      fullPath: '/admin/teachers/'
      preLoaderRoute: typeof AdminTeachersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students/': {
      id: '/admin/students/'
      path: '/students'
      fullPath: '/admin/students/'
      preLoaderRoute: typeof AdminStudentsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/classes/': {
      id: '/admin/classes/'
      path: '/classes'
      fullPath: '/admin/classes/'
      preLoaderRoute: typeof AdminClassesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/admissions/': {
      id: '/admin/admissions/'
      path: '/admissions'
      fullPath: '/admin/admissions/'
      preLoaderRoute: typeof AdminAdmissionsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/teachers/new': {
      id: '/admin/teachers/new'
      path: '/teachers/new'
      fullPath: '/admin/teachers/new'
      preLoaderRoute: typeof AdminTeachersNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students/new': {
      id: '/admin/students/new'
      path: '/students/new'
      fullPath: '/admin/students/new'
      preLoaderRoute: typeof AdminStudentsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students/$studentId/': {
      id: '/admin/students/$studentId/'
      path: '/students/$studentId'
      fullPath: '/admin/students/$studentId/'
      preLoaderRoute: typeof AdminStudentsStudentIdIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/teachers/$teacherId/edit': {
      id: '/admin/teachers/$teacherId/edit'
      path: '/teachers/$teacherId/edit'
      fullPath: '/admin/teachers/$teacherId/edit'
      preLoaderRoute: typeof AdminTeachersTeacherIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students/$studentId/edit': {
      id: '/admin/students/$studentId/edit'
      path: '/students/$studentId/edit'
      fullPath: '/admin/students/$studentId/edit'
      preLoaderRoute: typeof AdminStudentsStudentIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminActivitiesRoute: typeof AdminActivitiesRoute
  AdminApprovalsRoute: typeof AdminApprovalsRoute
  AdminAttendanceRoute: typeof AdminAttendanceRoute
  AdminAuditTrailRoute: typeof AdminAuditTrailRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminExamsRoute: typeof AdminExamsRoute
  AdminFeesRoute: typeof AdminFeesRoute
  AdminPerformanceRoute: typeof AdminPerformanceRoute
  AdminPtmRoute: typeof AdminPtmRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminVerificationRoute: typeof AdminVerificationRoute
  AdminStudentsNewRoute: typeof AdminStudentsNewRoute
  AdminTeachersNewRoute: typeof AdminTeachersNewRoute
  AdminAdmissionsIndexRoute: typeof AdminAdmissionsIndexRoute
  AdminClassesIndexRoute: typeof AdminClassesIndexRoute
  AdminStudentsIndexRoute: typeof AdminStudentsIndexRoute
  AdminTeachersIndexRoute: typeof AdminTeachersIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  AdminStudentsStudentIdEditRoute: typeof AdminStudentsStudentIdEditRoute
  AdminTeachersTeacherIdEditRoute: typeof AdminTeachersTeacherIdEditRoute
  AdminStudentsStudentIdIndexRoute: typeof AdminStudentsStudentIdIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActivitiesRoute: AdminActivitiesRoute,
  AdminApprovalsRoute: AdminApprovalsRoute,
  AdminAttendanceRoute: AdminAttendanceRoute,
  AdminAuditTrailRoute: AdminAuditTrailRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminExamsRoute: AdminExamsRoute,
  AdminFeesRoute: AdminFeesRoute,
  AdminPerformanceRoute: AdminPerformanceRoute,
  AdminPtmRoute: AdminPtmRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminVerificationRoute: AdminVerificationRoute,
  AdminStudentsNewRoute: AdminStudentsNewRoute,
  AdminTeachersNewRoute: AdminTeachersNewRoute,
  AdminAdmissionsIndexRoute: AdminAdmissionsIndexRoute,
  AdminClassesIndexRoute: AdminClassesIndexRoute,
  AdminStudentsIndexRoute: AdminStudentsIndexRoute,
  AdminTeachersIndexRoute: AdminTeachersIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  AdminStudentsStudentIdEditRoute: AdminStudentsStudentIdEditRoute,
  AdminTeachersTeacherIdEditRoute: AdminTeachersTeacherIdEditRoute,
  AdminStudentsStudentIdIndexRoute: AdminStudentsStudentIdIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface OperatorRouteChildren {
  OperatorDashboardRoute: typeof OperatorDashboardRoute
  OperatorAttendanceIndexRoute: typeof OperatorAttendanceIndexRoute
  OperatorBulkIndexRoute: typeof OperatorBulkIndexRoute
  OperatorExamsIndexRoute: typeof OperatorExamsIndexRoute
  OperatorFeedbackIndexRoute: typeof OperatorFeedbackIndexRoute
  OperatorFeesIndexRoute: typeof OperatorFeesIndexRoute
  OperatorMarksIndexRoute: typeof OperatorMarksIndexRoute
  OperatorSubmissionsIndexRoute: typeof OperatorSubmissionsIndexRoute
}

const OperatorRouteChildren: OperatorRouteChildren = {
  OperatorDashboardRoute: OperatorDashboardRoute,
  OperatorAttendanceIndexRoute: OperatorAttendanceIndexRoute,
  OperatorBulkIndexRoute: OperatorBulkIndexRoute,
  OperatorExamsIndexRoute: OperatorExamsIndexRoute,
  OperatorFeedbackIndexRoute: OperatorFeedbackIndexRoute,
  OperatorFeesIndexRoute: OperatorFeesIndexRoute,
  OperatorMarksIndexRoute: OperatorMarksIndexRoute,
  OperatorSubmissionsIndexRoute: OperatorSubmissionsIndexRoute,
}

const OperatorRouteWithChildren = OperatorRoute._addFileChildren(
  OperatorRouteChildren,
)

interface ParentRouteChildren {
  ParentAttendanceRoute: typeof ParentAttendanceRoute
  ParentDashboardRoute: typeof ParentDashboardRoute
  ParentExamsRoute: typeof ParentExamsRoute
  ParentFeesRoute: typeof ParentFeesRoute
  ParentNotificationsRoute: typeof ParentNotificationsRoute
  ParentProgressRoute: typeof ParentProgressRoute
  ParentReportsRoute: typeof ParentReportsRoute
}

const ParentRouteChildren: ParentRouteChildren = {
  ParentAttendanceRoute: ParentAttendanceRoute,
  ParentDashboardRoute: ParentDashboardRoute,
  ParentExamsRoute: ParentExamsRoute,
  ParentFeesRoute: ParentFeesRoute,
  ParentNotificationsRoute: ParentNotificationsRoute,
  ParentProgressRoute: ParentProgressRoute,
  ParentReportsRoute: ParentReportsRoute,
}

const ParentRouteWithChildren =
  ParentRoute._addFileChildren(ParentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OperatorRoute: OperatorRouteWithChildren,
  ParentRoute: ParentRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
